# Card Ranks
ACE = 'A'
TWO = '2'
THREE = '3'
FOUR = '4'
FIVE = '5'
SIX = '6'
SEVEN = '7'
EIGHT = '8'
NINE = '9'
TEN = 'T'
JACK = 'J'
QUEEN = 'Q'
KING = 'K'
JOKER = 'X' 

RANKS = [ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING]
ALL_RANKS = RANKS + [JOKER]

# Card Suits
HEARTS = 'H'
DIAMONDS = 'D'
CLUBS = 'C'
SPADES = 'S'
JOKER_SUIT = 'J' 

SUITS = [HEARTS, DIAMONDS, CLUBS, SPADES]
ALL_SUITS = SUITS + [JOKER_SUIT] 

# Grid Size
GRID_SIZE = 9
GRID_DIM = 3 # 3x3 grid
